AFGHANISTAN="AFGHANISTAN"
ALBANIA="ALBANIA"
ALGERIA="ALGERIA"
AMERICAN_SAMOA="AMERICAN_SAMOA"
ANDORRA="ANDORRA"
ANGOLA="ANGOLA"
ANGUILLA="ANGUILLA"
ANTIGUA_AND_BARBUDA="ANTIGUA_AND_BARBUDA"
ARGENTINA="ARGENTINA"
ARMENIA="ARMENIA"
ARUBA="ARUBA"
AUSTRALIA="AUSTRALIA"
AUSTRIA="AUSTRIA"
AZERBAIJAN="AZERBAIJAN"
BAHAMAS="BAHAMAS"
BAHRAIN="BAHRAIN"
BANGLADESH="BANGLADESH"
BARBADOS="BARBADOS"
BELARUS="BELARUS"
BELGIUM="BELGIUM"
BELIZE="BELIZE"
BENIN="BENIN"
BERMUDA="BERMUDA"
BHUTAN="BHUTAN"
BOLIVIA="BOLIVIA"
BONAIRE="BONAIRE"
BOSNIA_AND_HERZEGOVINA="BOSNIA_AND_HERZEGOVINA"
BOTSWANA="BOTSWANA"
BRAZIL="BRAZIL"
BRITISH_INDIAN_OCEAN_TER="BRITISH_INDIAN_OCEAN_TER"
BRUNEI="BRUNEI"
BULGARIA="BULGARIA"
BURKINA_FASO="BURKINA_FASO"
BURUNDI="BURUNDI"
CAMBODIA="CAMBODIA"
CAMEROON="CAMEROON"
CANADA="CANADA"
CANARY_ISLANDS="CANARY_ISLANDS"
CAPE_VERDE="CAPE_VERDE"
CAYMAN_ISLANDS="CAYMAN_ISLANDS"
CENTRAL_AFRICAN_REPUBLIC="CENTRAL_AFRICAN_REPUBLIC"
CHAD="CHAD"
CHANNEL_ISLANDS="CHANNEL_ISLANDS"
CHILE="CHILE"
CHINA="CHINA"
CHRISTMAS_ISLAND="CHRISTMAS_ISLAND"
COCOS_ISLAND="COCOS_ISLAND"
COLOMBIA="COLOMBIA"
COMOROS="COMOROS"
CONGO="CONGO"
COOK_ISLANDS="COOK_ISLANDS"
COSTA_RICA="COSTA_RICA"
COTE_DIVOIRE="COTE_DIVOIRE"
CROATIA="CROATIA"
CUBA="CUBA"
CURACO="CURACO"
CYPRUS="CYPRUS"
CZECH_REPUBLIC="CZECH_REPUBLIC"
DENMARK="DENMARK"
DJIBOUTI="DJIBOUTI"
DOMINICA="DOMINICA"
DOMINICAN_REPUBLIC="DOMINICAN_REPUBLIC"
EAST_TIMOR="EAST_TIMOR"
ECUADOR="ECUADOR"
EGYPT="EGYPT"
EL_SALVADOR="EL_SALVADOR"
EQUATORIAL_GUINEA="EQUATORIAL_GUINEA"
ERITREA="ERITREA"
ESTONIA="ESTONIA"
ETHIOPIA="ETHIOPIA"
FALKLAND_ISLANDS="FALKLAND_ISLANDS"
FAROE_ISLANDS="FAROE_ISLANDS"
FIJI="FIJI"
FINLAND="FINLAND"
FRANCE="FRANCE"
FRENCH_GUIANA="FRENCH_GUIANA"
FRENCH_POLYNESIA="FRENCH_POLYNESIA"
FRENCH_SOUTHERN_TER="FRENCH_SOUTHERN_TER"
GABON="GABON"
GAMBIA="GAMBIA"
GEORGIA="GEORGIA"
GERMANY="GERMANY"
GHANA="GHANA"
GIBRALTAR="GIBRALTAR"
GREAT_BRITAIN="GREAT_BRITAIN"
GREECE="GREECE"
GREENLAND="GREENLAND"
GRENADA="GRENADA"
GUADELOUPE="GUADELOUPE"
GUAM="GUAM"
GUATEMALA="GUATEMALA"
GUINEA="GUINEA"
GUYANA="GUYANA"
HAITI="HAITI"
HAWAII="HAWAII"
HONDURAS="HONDURAS"
HONG_KONG="HONG_KONG"
HUNGARY="HUNGARY"
ICELAND="ICELAND"
INDONESIA="INDONESIA"
INDIA="INDIA"
IRAN="IRAN"
IRAQ="IRAQ"
IRELAND="IRELAND"
ISLE_OF_MAN="ISLE_OF_MAN"
ISRAEL="ISRAEL"
ITALY="ITALY"
JAMAICA="JAMAICA"
JAPAN="JAPAN"
JORDAN="JORDAN"
KAZAKHSTAN="KAZAKHSTAN"
KENYA="KENYA"
KIRIBATI="KIRIBATI"
NORTH_KOREA="NORTH_KOREA"
SOUTH_KOREA="SOUTH_KOREA"
KUWAIT="KUWAIT"
KYRGYZSTAN="KYRGYZSTAN"
LAOS="LAOS"
LATVIA="LATVIA"
LEBANON="LEBANON"
LESOTHO="LESOTHO"
LIBERIA="LIBERIA"
LIBYA="LIBYA"
LIECHTENSTEIN="LIECHTENSTEIN"
LITHUANIA="LITHUANIA"
LUXEMBOURG="LUXEMBOURG"
MACAU="MACAU"
MACEDONIA="MACEDONIA"
MADAGASCAR="MADAGASCAR"
MALAYSIA="MALAYSIA"
MALAWI="MALAWI"
MALDIVES="MALDIVES"
MALI="MALI"
MALTA="MALTA"
MARSHALL_ISLANDS="MARSHALL_ISLANDS"
MARTINIQUE="MARTINIQUE"
MAURITANIA="MAURITANIA"
MAURITIUS="MAURITIUS"
MAYOTTE="MAYOTTE"
MEXICO="MEXICO"
MIDWAY_ISLANDS="MIDWAY_ISLANDS"
MOLDOVA="MOLDOVA"
MONACO="MONACO"
MONGOLIA="MONGOLIA"
MONTSERRAT="MONTSERRAT"
MOROCCO="MOROCCO"
MOZAMBIQUE="MOZAMBIQUE"
MYANMAR="MYANMAR"
NAMBIA="NAMBIA"
NAURU="NAURU"
NEPAL="NEPAL"
NETHERLANDS_ANTILLES="NETHERLANDS_ANTILLES"
NETHERLANDS="NETHERLANDS"
NEVIS="NEVIS"
NEW_CALEDONIA="NEW_CALEDONIA"
NEW_ZEALAND="NEW_ZEALAND"
NICARAGUA="NICARAGUA"
NIGER="NIGER"
NIGERIA="NIGERIA"
NIUE="NIUE"
NORFOLK_ISLAND="NORFOLK_ISLAND"
NORWAY="NORWAY"
OMAN="OMAN"
PAKISTAN="PAKISTAN"
PALAU_ISLAND="PALAU_ISLAND"
PALESTINE="PALESTINE"
PANAMA="PANAMA"
PAPUA_NEW_GUINEA="PAPUA_NEW_GUINEA"
PARAGUAY="PARAGUAY"
PERU="PERU"
PHILIPPINES="PHILIPPINES"
PITCAIRN_ISLAND="PITCAIRN_ISLAND"
POLAND="POLAND"
PORTUGAL="PORTUGAL"
PUERTO_RICO="PUERTO_RICO"
QATAR="QATAR"
REPUBLIC_OF_MONTENEGRO="REPUBLIC_OF_MONTENEGRO"
REPUBLIC_OF_SERBIA="REPUBLIC_OF_SERBIA"
REUNION="REUNION"
ROMANIA="ROMANIA"
RUSSIA="RUSSIA"
RWANDA="RWANDA"
ST_BARTHOLEMY="ST_BARTHOLEMY"
ST_EUSTATIUS="ST_EUSTATIUS"
ST_HELENA="ST_HELENA"
ST_KITTS_NEVIS="ST_KITTS_NEVIS"
ST_LUCIA="ST_LUCIA"
ST_MAARTEN="ST_MAARTEN"
ST_PIERRE_AND_MIQUELON="ST_PIERRE_AND_MIQUELON"
ST_VINCENT_AND_GRENADINES="ST_VINCENT_AND_GRENADINES"
SAIPAN="SAIPAN"
SAMOA="SAMOA"
SAMOA_AMERICAN="SAMOA_AMERICAN"
SAN_MARINO="SAN_MARINO"
SAO_TOME_AND_PRINCIPE="SAO_TOME_AND_PRINCIPE"
SAUDI_ARABIA="SAUDI_ARABIA"
SENEGAL="SENEGAL"
SEYCHELLES="SEYCHELLES"
SIERRA_LEONE="SIERRA_LEONE"
SINGAPORE="SINGAPORE"
SLOVAKIA="SLOVAKIA"
SLOVENIA="SLOVENIA"
SOLOMON_ISLANDS="SOLOMON_ISLANDS"
SOMALIA="SOMALIA"
SOUTH_AFRICA="SOUTH_AFRICA"
SPAIN="SPAIN"
SRI_LANKA="SRI_LANKA"
SUDAN="SUDAN"
SURINAME="SURINAME"
SWAZILAND="SWAZILAND"
SWEDEN="SWEDEN"
SWITZERLAND="SWITZERLAND"
SYRIA="SYRIA"
TAHITI="TAHITI"
TAIWAN="TAIWAN"
TAJIKISTAN="TAJIKISTAN"
TANZANIA="TANZANIA"
THAILAND="THAILAND"
TOGO="TOGO"
TOKELAU="TOKELAU"
TONGA="TONGA"
TRINIDAD_AND_TOBAGO="TRINIDAD_AND_TOBAGO"
TUNISIA="TUNISIA"
TURKEY="TURKEY"
TURKMENISTAN="TURKMENISTAN"
TURKS_AND_CAICOS_IS="TURKS_AND_CAICOS_IS"
TUVALU="TUVALU"
UGANDA="UGANDA"
UNITED_KINGDOM="UNITED_KINGDOM"
UKRAINE="UKRAINE"
UNITED_ARAB_ERIMATES="UNITED_ARAB_ERIMATES"
UNITED_STATES_OF_AMERICA="UNITED_STATES_OF_AMERICA"
URUGUAY="URUGUAY"
UZBEKISTAN="UZBEKISTAN"
VANUATU="VANUATU"
VATICAN_CITY_STATE="VATICAN_CITY_STATE"
VENEZUELA="VENEZUELA"
VIETNAM="VIETNAM"
VIRGIN_ISLANDS_BRIT="VIRGIN_ISLANDS_BRIT"
VIRGIN_ISLANDS_USA="VIRGIN_ISLANDS_USA"
WAKE_ISLAND="WAKE_ISLAND"
WALLIS_AND_FUTANA_IS="WALLIS_AND_FUTANA_IS"
YEMEN="YEMEN"
ZAIRE="ZAIRE"
ZAMBIA="ZAMBIA"
ZIMBABWE="ZIMBABWE"
KOREA="KOREA"
SERBIA="SERBIA"
NONE="NONE"

COUNTRIES = (
    (AFGHANISTAN, "Afghanistan"),
    (ALBANIA, "Albania"),
    (ALGERIA, "Algeria"),
    (AMERICAN_SAMOA, "American Samoa"),
    (ANDORRA, "Andorra"),
    (ANGOLA, "Angola"),
    (ANGUILLA, "Anguilla"),
    (ANTIGUA_AND_BARBUDA, "Antigua and Barbuda"),
    (ARGENTINA, "Argentina"),
    (ARMENIA, "Armenia"),
    (ARUBA, "Aruba"),
    (AUSTRALIA, "Australia"),
    (AUSTRIA, "Austria"),
    (AZERBAIJAN, "Azerbaijan"),
    (BAHAMAS, "Bahamas"),
    (BAHRAIN, "Bahrain"),
    (BANGLADESH, "Bangladesh"),
    (BARBADOS, "Barbados"),
    (BELARUS, "Belarus"),
    (BELGIUM, "Belgium"),
    (BELIZE, "Belize"),
    (BENIN, "Benin"),
    (BERMUDA, "Bermuda"),
    (BHUTAN, "Bhutan"),
    (BOLIVIA, "Bolivia"),
    (BONAIRE, "Bonaire"),
    (BOSNIA_AND_HERZEGOVINA, "Bosnia and Herzegovina"),
    (BOTSWANA, "Botswana"),
    (BRAZIL, "Brazil"),
    (BRITISH_INDIAN_OCEAN_TER, "British Indian Ocean Ter"),
    (BRUNEI, "Brunei"),
    (BULGARIA, "Bulgaria"),
    (BURKINA_FASO, "Burkina Faso"),
    (BURUNDI, "Burundi"),
    (CAMBODIA, "Cambodia"),
    (CAMEROON, "Cameroon"),
    (CANADA, "Canada"),
    (CANARY_ISLANDS, "Canary Islands"),
    (CAPE_VERDE, "Cape Verde"),
    (CAYMAN_ISLANDS, "Cayman Islands"),
    (CENTRAL_AFRICAN_REPUBLIC, "Central African Republic"),
    (CHAD, "Chad"),
    (CHANNEL_ISLANDS, "Channel Islands"),
    (CHILE, "Chile"),
    (CHINA, "China"),
    (CHRISTMAS_ISLAND, "Christmas Island"),
    (COCOS_ISLAND, "Cocos Island"),
    (COLOMBIA, "Colombia"),
    (COMOROS, "Comoros"),
    (CONGO, "Congo"),
    (COOK_ISLANDS, "Cook Islands"),
    (COSTA_RICA, "Costa Rica"),
    (COTE_DIVOIRE, "Cote DIvoire"),
    (CROATIA, "Croatia"),
    (CUBA, "Cuba"),
    (CURACO, "Curaco"),
    (CYPRUS, "Cyprus"),
    (CZECH_REPUBLIC, "Czech Republic"),
    (DENMARK, "Denmark"),
    (DJIBOUTI, "Djibouti"),
    (DOMINICA, "Dominica"),
    (DOMINICAN_REPUBLIC, "Dominican Republic"),
    (EAST_TIMOR, "East Timor"),
    (ECUADOR, "Ecuador"),
    (EGYPT, "Egypt"),
    (EL_SALVADOR, "El Salvador"),
    (EQUATORIAL_GUINEA, "Equatorial Guinea"),
    (ERITREA, "Eritrea"),
    (ESTONIA, "Estonia"),
    (ETHIOPIA, "Ethiopia"),
    (FALKLAND_ISLANDS, "Falkland Islands"),
    (FAROE_ISLANDS, "Faroe Islands"),
    (FIJI, "Fiji"),
    (FINLAND, "Finland"),
    (FRANCE, "France"),
    (FRENCH_GUIANA, "French Guiana"),
    (FRENCH_POLYNESIA, "French Polynesia"),
    (FRENCH_SOUTHERN_TER, "French Southern Ter"),
    (GABON, "Gabon"),
    (GAMBIA, "Gambia"),
    (GEORGIA, "Georgia"),
    (GERMANY, "Germany"),
    (GHANA, "Ghana"),
    (GIBRALTAR, "Gibraltar"),
    (GREAT_BRITAIN, "Great Britain"),
    (GREECE, "Greece"),
    (GREENLAND, "Greenland"),
    (GRENADA, "Grenada"),
    (GUADELOUPE, "Guadeloupe"),
    (GUAM, "Guam"),
    (GUATEMALA, "Guatemala"),
    (GUINEA, "Guinea"),
    (GUYANA, "Guyana"),
    (HAITI, "Haiti"),
    (HAWAII, "Hawaii"),
    (HONDURAS, "Honduras"),
    (HONG_KONG, "Hong Kong"),
    (HUNGARY, "Hungary"),
    (ICELAND, "Iceland"),
    (INDONESIA, "Indonesia"),
    (INDIA, "India"),
    (IRAN, "Iran"),
    (IRAQ, "Iraq"),
    (IRELAND, "Ireland"),
    (ISLE_OF_MAN, "Isle of Man"),
    (ISRAEL, "Israel"),
    (ITALY, "Italy"),
    (JAMAICA, "Jamaica"),
    (JAPAN, "Japan"),
    (JORDAN, "Jordan"),
    (KAZAKHSTAN, "Kazakhstan"),
    (KENYA, "Kenya"),
    (KIRIBATI, "Kiribati"),
    (NORTH_KOREA, "North Korea"),
    (SOUTH_KOREA, "South Korea"),
    (KUWAIT, "Kuwait"),
    (KYRGYZSTAN, "Kyrgyzstan"),
    (LAOS, "Laos"),
    (LATVIA, "Latvia"),
    (LEBANON, "Lebanon"),
    (LESOTHO, "Lesotho"),
    (LIBERIA, "Liberia"),
    (LIBYA, "Libya"),
    (LIECHTENSTEIN, "Liechtenstein"),
    (LITHUANIA, "Lithuania"),
    (LUXEMBOURG, "Luxembourg"),
    (MACAU, "Macau"),
    (MACEDONIA, "Macedonia"),
    (MADAGASCAR, "Madagascar"),
    (MALAYSIA, "Malaysia"),
    (MALAWI, "Malawi"),
    (MALDIVES, "Maldives"),
    (MALI, "Mali"),
    (MALTA, "Malta"),
    (MARSHALL_ISLANDS, "Marshall Islands"),
    (MARTINIQUE, "Martinique"),
    (MAURITANIA, "Mauritania"),
    (MAURITIUS, "Mauritius"),
    (MAYOTTE, "Mayotte"),
    (MEXICO, "Mexico"),
    (MIDWAY_ISLANDS, "Midway Islands"),
    (MOLDOVA, "Moldova"),
    (MONACO, "Monaco"),
    (MONGOLIA, "Mongolia"),
    (MONTSERRAT, "Montserrat"),
    (MOROCCO, "Morocco"),
    (MOZAMBIQUE, "Mozambique"),
    (MYANMAR, "Myanmar"),
    (NAMBIA, "Nambia"),
    (NAURU, "Nauru"),
    (NEPAL, "Nepal"),
    (NETHERLANDS_ANTILLES, "Netherlands Antilles"),
    (NETHERLANDS, "Netherlands"),
    (NEVIS, "Nevis"),
    (NEW_CALEDONIA, "New Caledonia"),
    (NEW_ZEALAND, "New Zealand"),
    (NICARAGUA, "Nicaragua"),
    (NIGER, "Niger"),
    (NIGERIA, "Nigeria"),
    (NIUE, "Niue"),
    (NORFOLK_ISLAND, "Norfolk Island"),
    (NORWAY, "Norway"),
    (OMAN, "Oman"),
    (PAKISTAN, "Pakistan"),
    (PALAU_ISLAND, "Palau Island"),
    (PALESTINE, "Palestine"),
    (PANAMA, "Panama"),
    (PAPUA_NEW_GUINEA, "Papua New Guinea"),
    (PARAGUAY, "Paraguay"),
    (PERU, "Peru"),
    (PHILIPPINES, "Philippines"),
    (PITCAIRN_ISLAND, "Pitcairn Island"),
    (POLAND, "Poland"),
    (PORTUGAL, "Portugal"),
    (PUERTO_RICO, "Puerto Rico"),
    (QATAR, "Qatar"),
    (REPUBLIC_OF_MONTENEGRO, "Republic of Montenegro"),
    (REPUBLIC_OF_SERBIA, "Republic of Serbia"),
    (REUNION, "Reunion"),
    (ROMANIA, "Romania"),
    (RUSSIA, "Russia"),
    (RWANDA, "Rwanda"),
    (ST_BARTHOLEMY, "St Bartholemy"),
    (ST_EUSTATIUS, "St Eustatius"),
    (ST_HELENA, "St Helena"),
    (ST_KITTS_NEVIS, "St Kitts-Nevis"),
    (ST_LUCIA, "St Lucia"),
    (ST_MAARTEN, "St Maarten"),
    (ST_PIERRE_AND_MIQUELON, "St Pierre and Miquelon"),
    (ST_VINCENT_AND_GRENADINES, "St Vincent and Grenadines"),
    (SAIPAN, "Saipan"),
    (SAMOA, "Samoa"),
    (SAMOA_AMERICAN, "Samoa American"),
    (SAN_MARINO, "San Marino"),
    (SAO_TOME_AND_PRINCIPE, "Sao Tome and Principe"),
    (SAUDI_ARABIA, "Saudi Arabia"),
    (SENEGAL, "Senegal"),
    (SEYCHELLES, "Seychelles"),
    (SIERRA_LEONE, "Sierra Leone"),
    (SINGAPORE, "Singapore"),
    (SLOVAKIA, "Slovakia"),
    (SLOVENIA, "Slovenia"),
    (SOLOMON_ISLANDS, "Solomon Islands"),
    (SOMALIA, "Somalia"),
    (SOUTH_AFRICA, "South Africa"),
    (SPAIN, "Spain"),
    (SRI_LANKA, "Sri Lanka"),
    (SUDAN, "Sudan"),
    (SURINAME, "Suriname"),
    (SWAZILAND, "Swaziland"),
    (SWEDEN, "Sweden"),
    (SWITZERLAND, "Switzerland"),
    (SYRIA, "Syria"),
    (TAHITI, "Tahiti"),
    (TAIWAN, "Taiwan"),
    (TAJIKISTAN, "Tajikistan"),
    (TANZANIA, "Tanzania"),
    (THAILAND, "Thailand"),
    (TOGO, "Togo"),
    (TOKELAU, "Tokelau"),
    (TONGA, "Tonga"),
    (TRINIDAD_AND_TOBAGO, "Trinidad and Tobago"),
    (TUNISIA, "Tunisia"),
    (TURKEY, "Turkey"),
    (TURKMENISTAN, "Turkmenistan"),
    (TURKS_AND_CAICOS_IS, "Turks and Caicos Is"),
    (TUVALU, "Tuvalu"),
    (UGANDA, "Uganda"),
    (UNITED_KINGDOM, "United Kingdom"),
    (UKRAINE, "Ukraine"),
    (UNITED_ARAB_ERIMATES, "United Arab Erimates"),
    (UNITED_STATES_OF_AMERICA, "United States of America"),
    (URUGUAY, "Uruguay"),
    (UZBEKISTAN, "Uzbekistan"),
    (VANUATU, "Vanuatu"),
    (VATICAN_CITY_STATE, "Vatican City State"),
    (VENEZUELA, "Venezuela"),
    (VIETNAM, "Vietnam"),
    (VIRGIN_ISLANDS_BRIT, "Virgin Islands (Brit)"),
    (VIRGIN_ISLANDS_USA, "Virgin Islands (USA)"),
    (WAKE_ISLAND, "Wake Island"),
    (WALLIS_AND_FUTANA_IS, "Wallis and Futana Is"),
    (YEMEN, "Yemen"),
    (ZAIRE, "Zaire"),
    (ZAMBIA, "Zambia"),
    (ZIMBABWE, "Zimbabwe"),
    (KOREA, "Korea"),
    (SERBIA, "Serbia"),
    (NONE, "None")
)