# Generated by Django 2.1.5 on 2019-01-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.SlugField(blank=True, max_length=31, unique=True),
        ),
    ]
