# Generated by Django 2.2 on 2019-08-24 11:34

from django.db import migrations, models
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='field_of_study',
            new_name='field',
        ),
        migrations.AddField(
            model_name='paper',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to=formula_one.utils.upload_to.UploadTo('common_biodata', 'papers')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.SlugField(blank=True, max_length=31, unique=True),
        ),
    ]
