# Generated by Django 2.2 on 2019-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0002_auto_20190824_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
