# Generated by Django 2.2.3 on 2019-08-29 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0003_profile_personal_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingengagement',
            old_name='course',
            new_name='course_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personal_website',
        ),
        migrations.AddField(
            model_name='teachingengagement',
            name='course_title',
            field=models.CharField(default='EEN', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='faculty_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_FACULTYMEMBER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachingengagement',
            name='class_name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='teachingengagement',
            name='lecture_hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachingengagement',
            name='practical_hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachingengagement',
            name='tutorial_hours',
            field=models.IntegerField(blank=True),
        ),
    ]
