# Generated by Django 2.2.6 on 2019-12-14 21:07

from django.db import migrations, models
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0004_auto_20190830_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='administrativeposition',
            name='scope',
            field=models.CharField(choices=[('d', 'Departmental'), ('c', 'Central'), ('i', 'Institute'), ('e', 'External')], max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('con', 'Conference'), ('gue', 'Guest lecture'), ('sem', 'Seminar'), ('stc', 'Short term course'), ('spl', 'Special lecture'), ('tlk', 'Talk'), ('oth', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='role',
            field=models.CharField(choices=[('o', 'Organiser'), ('a', 'Attendee'), ('i', 'Invitee')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=formula_one.utils.upload_to.UploadTo('faculty_biodata', 'resume')),
        ),
    ]
