# Generated by Django 2.2.6 on 2019-12-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0005_auto_20191215_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='scholars_name',
            field=models.TextField(blank=True),
        ),
    ]
