# Generated by Django 2.2.6 on 2019-12-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0007_auto_20191216_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatescholar',
            name='home_page',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='name_of_other_supervisors',
            field=models.TextField(blank=True),
        ),
    ]
