# Generated by Django 2.2.6 on 2020-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0010_auto_20200124_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supervision',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
