# Generated by Django 3.0.3 on 2020-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0011_auto_20200622_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='level',
            field=models.CharField(blank=True, choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('phd', 'PhD'), ('rp', 'Research Project'), ('oth', 'Other')], max_length=3),
        ),
        migrations.AddField(
            model_name='supervision',
            name='phd_type',
            field=models.CharField(blank=True, choices=[('f', 'Fulltime'), ('p', 'Parttime')], max_length=1),
        ),
        migrations.AddField(
            model_name='teachingengagement',
            name='semester',
            field=models.CharField(choices=[('s', 'Spring'), ('a', 'Autumn')], default='s', max_length=1),
        ),
    ]
