# Generated by Django 2.2.6 on 2020-06-26 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_FACULTYMEMBER_MODEL),
        ('faculty_biodata', '0012_auto_20200626_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatescholar',
            name='interest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_FACULTYMEMBER_MODEL)),
            ],
            options={
                'swappable': 'FACULTY_BIODATA_MISCELLANEOUS_MODEL',
            },
        ),
    ]
