# Generated by Django 2.2.6 on 2020-06-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0013_auto_20200627_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingengagement',
            name='lecture_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachingengagement',
            name='practical_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachingengagement',
            name='tutorial_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
