# Generated by Django 3.0.3 on 2020-07-05 05:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0014_auto_20200628_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneous',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
