# Generated by Django 3.0.3 on 2020-07-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0016_auto_20200707_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatescholar',
            name='interest',
            field=models.CharField(max_length=255),
        ),
    ]
