# Generated by Django 3.0.3 on 2020-07-24 09:52

from django.db import migrations, models
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0017_auto_20200715_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='file',
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to=formula_one.utils.upload_to.UploadTo('faculty_biodata', 'papers')),
        ),
    ]
