# Generated by Django 3.0.3 on 2020-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0018_auto_20200724_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation',
            field=models.CharField(choices=[('mat', 'Matriculate (Class X)'), ('int', 'Intermediate (Class XII)'), ('dip', 'Diploma'), ('ass', 'Associate'), ('gra', 'Graduate (UG)'), ('pos', 'Postgraduate (PG)'), ('doc', 'Doctorate (PhD)'), ('pdo', 'Postdoctorate (Postdoc)')], max_length=3),
        ),
    ]
