# Generated by Django 3.0.3 on 2020-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0018_auto_20200724_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_full_date',
            field=models.BooleanField(default=False),
        ),
    ]
