# Generated by Django 3.0.3 on 2020-09-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_biodata', '0019_event_is_full_date'),
        ('faculty_biodata', '0019_auto_20200918_2015'),
    ]

    operations = [
    ]
