# Generated by Django 3.2.8 on 2022-05-24 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_FACULTYMEMBER_MODEL),
        ('faculty_biodata', '0021_auto_20210502_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_full_date', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=127)),
                ('organisation', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
                ('faculty_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_FACULTYMEMBER_MODEL)),
            ],
            options={
                'swappable': 'FACULTY_BIODATA_PROFESSIONALBACKGROUND_MODEL',
            },
        ),
    ]
